In [1]:
import numpy as np
import pandas as pd

print("Employee Data Analysis System")

Employee Data Analysis System

In [2]:
df = pd.read_csv("../data/employees.csv")
df

    name   age department  salary
0   Teja  22.0         IT   55000
1  Rahul  25.0         HR   45000
2  Priya  28.0    Finance   60000
3  Arjun   NaN         IT   50000
4  Rahul  25.0         HR   45000
5  Sneha  30.0        NaN   65000

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        6 non-null      str
 1   age         5 non-null      float64
 2   department  5 non-null      str
 3   salary      6 non-null      int64
dtypes: float64(1), int64(1), str(2)
memory usage: 324.0 bytes

In [4]:
df.isnull().sum()

name          0
age           1
department    1
salary        0
dtype: int64

In [5]:
df["age"] = df["age"].fillna(df["age"].mean())
df["department"] = df["department"].fillna("Unknown")

df

    name   age department  salary
0   Teja  22.0         IT   55000
1  Rahul  25.0         HR   45000
2  Priya  28.0    Finance   60000
3  Arjun  26.0         IT   50000
4  Rahul  25.0         HR   45000
5  Sneha  30.0    Unknown   65000

In [6]:
df = df.drop_duplicates().reset_index(drop=True)
df

    name   age department  salary
0   Teja  22.0         IT   55000
1  Rahul  25.0         HR   45000
2  Priya  28.0    Finance   60000
3  Arjun  26.0         IT   50000
4  Sneha  30.0    Unknown   65000

In [7]:
df.groupby("department")["name"].count()

department
Finance    1
HR         1
IT         2
Unknown    1
Name: name, dtype: int64

In [8]:
df.groupby("department")["salary"].mean()

department
Finance    60000.0
HR         45000.0
IT         52500.0
Unknown    65000.0
Name: salary, dtype: float64

In [9]:
import numpy as np

print(np.__version__)

2.5.2